name: Sync Hagezi Pro++ Blocklist

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6:00 AM UTC
  workflow_dispatch:  # Allow manual trigger too

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Download latest Hagezi Pro++
        run: |
          curl -sSL https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.txt -o lists/hagezi_pro_plus.txt

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add lists/hagezi_pro_plus.txt
          git diff --cached --quiet || git commit -m "Auto-sync: Hagezi Pro++ updated"
          git push
